import type { Airport } from "./types";

// The airports this work knows about, as reference data rather than as part of
// any one surface. It was born inside the bench's mock flight, which was the
// wrong home the moment a second thing needed it: booking sells a seat on a
// route before there is a simulation to run, and both have to agree on what
// LHR is called and where it is.

export const AIRPORTS: Record<string, Airport> = {
  JFK: {
    iata: "JFK",
    photoTitle: "Manhattan",
    icao: "KJFK",
    city: {
      en: "New York",
      zh: "纽约",
      "zh-Hant": "紐約",
      ja: "ニューヨーク",
      es: "Nueva York",
      fr: "New York",
      ru: "Нью-Йорк",
    },
    name: { en: "John F. Kennedy Intl", zh: "肯尼迪国际机场" },
    country: { en: "United States", zh: "美国" },
    cc: "US",
    lat: 40.6413,
    lon: -73.7781,
    tz: "America/New_York",
  },
  LHR: {
    iata: "LHR",
    icao: "EGLL",
    city: {
      en: "London",
      zh: "伦敦",
      "zh-Hant": "倫敦",
      ja: "ロンドン",
      es: "Londres",
      fr: "Londres",
      ru: "Лондон",
    },
    name: { en: "Heathrow", zh: "希思罗机场" },
    country: { en: "United Kingdom", zh: "英国" },
    cc: "GB",
    lat: 51.47,
    lon: -0.4543,
    tz: "Europe/London",
  },
  PVG: {
    iata: "PVG",
    // Shanghai's own article leads with a photograph of Huangpu Park, which
    // is a park. The Bund is the view everybody means by Shanghai.
    photoTitle: "The Bund",
    icao: "ZSPD",
    city: {
      en: "Shanghai",
      zh: "上海",
      "zh-Hant": "上海",
      ja: "上海",
      es: "Shanghái",
      fr: "Shanghai",
      ru: "Шанхай",
    },
    name: { en: "Pudong Intl", zh: "浦东国际机场" },
    country: { en: "China", zh: "中国" },
    cc: "CN",
    lat: 31.1443,
    lon: 121.8083,
    tz: "Asia/Shanghai",
  },
  HND: {
    iata: "HND",
    icao: "RJTT",
    city: {
      en: "Tokyo",
      zh: "东京",
      "zh-Hant": "東京",
      ja: "東京",
      es: "Tokio",
      fr: "Tokyo",
      ru: "Токио",
    },
    name: { en: "Haneda", zh: "羽田机场" },
    country: { en: "Japan", zh: "日本" },
    cc: "JP",
    lat: 35.5533,
    lon: 139.7811,
    tz: "Asia/Tokyo",
  },
  LAX: {
    iata: "LAX",
    photoTitle: "Downtown Los Angeles",
    icao: "KLAX",
    city: {
      en: "Los Angeles",
      zh: "洛杉矶",
      "zh-Hant": "洛杉磯",
      ja: "ロサンゼルス",
      es: "Los Ángeles",
      fr: "Los Angeles",
      ru: "Лос-Анджелес",
    },
    name: { en: "Los Angeles Intl", zh: "洛杉矶国际机场" },
    country: { en: "United States", zh: "美国" },
    cc: "US",
    lat: 33.9416,
    lon: -118.4085,
    tz: "America/Los_Angeles",
  },
  CDG: {
    iata: "CDG",
    icao: "LFPG",
    city: {
      en: "Paris",
      zh: "巴黎",
      "zh-Hant": "巴黎",
      ja: "パリ",
      es: "París",
      fr: "Paris",
      ru: "Париж",
    },
    name: { en: "Charles de Gaulle", zh: "戴高乐机场" },
    country: { en: "France", zh: "法国" },
    cc: "FR",
    lat: 49.0097,
    lon: 2.5479,
    tz: "Europe/Paris",
  },
  SIN: {
    iata: "SIN",
    photoTitle: "Marina Bay Sands",
    icao: "WSSS",
    city: {
      en: "Singapore",
      zh: "新加坡",
      "zh-Hant": "新加坡",
      ja: "シンガポール",
      es: "Singapur",
      fr: "Singapour",
      ru: "Сингапур",
    },
    name: { en: "Changi", zh: "樟宜机场" },
    country: { en: "Singapore", zh: "新加坡" },
    cc: "SG",
    lat: 1.3644,
    lon: 103.9915,
    tz: "Asia/Singapore",
  },
  AMS: {
    iata: "AMS",
    icao: "EHAM",
    city: {
      en: "Amsterdam",
      zh: "阿姆斯特丹",
      "zh-Hant": "阿姆斯特丹",
      ja: "アムステルダム",
      es: "Ámsterdam",
      fr: "Amsterdam",
      ru: "Амстердам",
    },
    name: { en: "Schiphol", zh: "史基浦机场" },
    country: { en: "Netherlands", zh: "荷兰" },
    cc: "NL",
    lat: 52.3105,
    lon: 4.7683,
    tz: "Europe/Amsterdam",
  },
  FRA: {
    iata: "FRA",
    icao: "EDDF",
    city: {
      en: "Frankfurt",
      zh: "法兰克福",
      "zh-Hant": "法蘭克福",
      ja: "フランクフルト",
      es: "Fráncfort",
      fr: "Francfort",
      ru: "Франкфурт",
    },
    name: { en: "Frankfurt am Main", zh: "法兰克福机场" },
    country: { en: "Germany", zh: "德国" },
    cc: "DE",
    lat: 50.0379,
    lon: 8.5622,
    tz: "Europe/Berlin",
  },
  MUC: {
    iata: "MUC",
    icao: "EDDM",
    city: {
      en: "Munich",
      zh: "慕尼黑",
      "zh-Hant": "慕尼黑",
      ja: "ミュンヘン",
      es: "Múnich",
      fr: "Munich",
      ru: "Мюнхен",
    },
    name: { en: "Franz Josef Strauss", zh: "慕尼黑机场" },
    country: { en: "Germany", zh: "德国" },
    cc: "DE",
    lat: 48.3538,
    lon: 11.7861,
    tz: "Europe/Berlin",
  },
  MAD: {
    iata: "MAD",
    icao: "LEMD",
    city: {
      en: "Madrid",
      zh: "马德里",
      "zh-Hant": "馬德里",
      ja: "マドリード",
      es: "Madrid",
      fr: "Madrid",
      ru: "Мадрид",
    },
    name: { en: "Barajas", zh: "巴拉哈斯机场" },
    country: { en: "Spain", zh: "西班牙" },
    cc: "ES",
    lat: 40.4719,
    lon: -3.5626,
    tz: "Europe/Madrid",
  },
  BCN: {
    iata: "BCN",
    icao: "LEBL",
    city: {
      en: "Barcelona",
      zh: "巴塞罗那",
      "zh-Hant": "巴塞隆納",
      ja: "バルセロナ",
      es: "Barcelona",
      fr: "Barcelone",
      ru: "Барселона",
    },
    name: { en: "El Prat", zh: "埃尔普拉特机场" },
    country: { en: "Spain", zh: "西班牙" },
    cc: "ES",
    lat: 41.2974,
    lon: 2.0833,
    tz: "Europe/Madrid",
  },
  FCO: {
    iata: "FCO",
    icao: "LIRF",
    city: {
      en: "Rome",
      zh: "罗马",
      "zh-Hant": "羅馬",
      ja: "ローマ",
      es: "Roma",
      fr: "Rome",
      ru: "Рим",
    },
    name: { en: "Fiumicino", zh: "菲乌米奇诺机场" },
    country: { en: "Italy", zh: "意大利" },
    cc: "IT",
    lat: 41.8003,
    lon: 12.2389,
    tz: "Europe/Rome",
  },
  MXP: {
    iata: "MXP",
    icao: "LIMC",
    city: {
      en: "Milan",
      zh: "米兰",
      "zh-Hant": "米蘭",
      ja: "ミラノ",
      es: "Milán",
      fr: "Milan",
      ru: "Милан",
    },
    name: { en: "Malpensa", zh: "马尔彭萨机场" },
    country: { en: "Italy", zh: "意大利" },
    cc: "IT",
    lat: 45.6306,
    lon: 8.7281,
    tz: "Europe/Rome",
  },
  ZRH: {
    iata: "ZRH",
    icao: "LSZH",
    city: {
      en: "Zurich",
      zh: "苏黎世",
      "zh-Hant": "蘇黎世",
      ja: "チューリッヒ",
      es: "Zúrich",
      fr: "Zurich",
      ru: "Цюрих",
    },
    name: { en: "Zurich", zh: "苏黎世机场" },
    country: { en: "Switzerland", zh: "瑞士" },
    cc: "CH",
    lat: 47.4647,
    lon: 8.5492,
    tz: "Europe/Zurich",
  },
  VIE: {
    iata: "VIE",
    icao: "LOWW",
    city: {
      en: "Vienna",
      zh: "维也纳",
      "zh-Hant": "維也納",
      ja: "ウィーン",
      es: "Viena",
      fr: "Vienne",
      ru: "Вена",
    },
    name: { en: "Schwechat", zh: "施韦夏特机场" },
    country: { en: "Austria", zh: "奥地利" },
    cc: "AT",
    lat: 48.1103,
    lon: 16.5697,
    tz: "Europe/Vienna",
  },
  CPH: {
    iata: "CPH",
    icao: "EKCH",
    city: {
      en: "Copenhagen",
      zh: "哥本哈根",
      "zh-Hant": "哥本哈根",
      ja: "コペンハーゲン",
      es: "Copenhague",
      fr: "Copenhague",
      ru: "Копенгаген",
    },
    name: { en: "Kastrup", zh: "凯斯楚普机场" },
    country: { en: "Denmark", zh: "丹麦" },
    cc: "DK",
    lat: 55.618,
    lon: 12.656,
    tz: "Europe/Copenhagen",
  },
  ARN: {
    iata: "ARN",
    icao: "ESSA",
    city: {
      en: "Stockholm",
      zh: "斯德哥尔摩",
      "zh-Hant": "斯德哥爾摩",
      ja: "ストックホルム",
      es: "Estocolmo",
      fr: "Stockholm",
      ru: "Стокгольм",
    },
    name: { en: "Arlanda", zh: "阿兰达机场" },
    country: { en: "Sweden", zh: "瑞典" },
    cc: "SE",
    lat: 59.6519,
    lon: 17.9186,
    tz: "Europe/Stockholm",
  },
  DUB: {
    iata: "DUB",
    icao: "EIDW",
    city: {
      en: "Dublin",
      zh: "都柏林",
      "zh-Hant": "都柏林",
      ja: "ダブリン",
      es: "Dublín",
      fr: "Dublin",
      ru: "Дублин",
    },
    name: { en: "Dublin", zh: "都柏林机场" },
    country: { en: "Ireland", zh: "爱尔兰" },
    cc: "IE",
    lat: 53.4213,
    lon: -6.2701,
    tz: "Europe/Dublin",
  },
  LIS: {
    iata: "LIS",
    icao: "LPPT",
    city: {
      en: "Lisbon",
      zh: "里斯本",
      "zh-Hant": "里斯本",
      ja: "リスボン",
      es: "Lisboa",
      fr: "Lisbonne",
      ru: "Лиссабон",
    },
    name: { en: "Humberto Delgado", zh: "乌贝尔图·德尔加杜机场" },
    country: { en: "Portugal", zh: "葡萄牙" },
    cc: "PT",
    lat: 38.7742,
    lon: -9.1342,
    tz: "Europe/Lisbon",
  },
  ATH: {
    iata: "ATH",
    icao: "LGAV",
    city: {
      en: "Athens",
      zh: "雅典",
      "zh-Hant": "雅典",
      ja: "アテネ",
      es: "Atenas",
      fr: "Athènes",
      ru: "Афины",
    },
    name: { en: "Eleftherios Venizelos", zh: "埃莱夫塞里奥斯·韦尼泽洛斯机场" },
    country: { en: "Greece", zh: "希腊" },
    cc: "GR",
    lat: 37.9364,
    lon: 23.9445,
    tz: "Europe/Athens",
  },
  BOS: {
    iata: "BOS",
    icao: "KBOS",
    city: {
      en: "Boston",
      zh: "波士顿",
      "zh-Hant": "波士頓",
      ja: "ボストン",
      es: "Boston",
      fr: "Boston",
      ru: "Бостон",
    },
    name: { en: "Logan Intl", zh: "洛根国际机场" },
    country: { en: "United States", zh: "美国" },
    cc: "US",
    lat: 42.3656,
    lon: -71.0096,
    tz: "America/New_York",
  },
  ORD: {
    iata: "ORD",
    icao: "KORD",
    city: {
      en: "Chicago",
      zh: "芝加哥",
      "zh-Hant": "芝加哥",
      ja: "シカゴ",
      es: "Chicago",
      fr: "Chicago",
      ru: "Чикаго",
    },
    name: { en: "O'Hare Intl", zh: "奥黑尔国际机场" },
    country: { en: "United States", zh: "美国" },
    cc: "US",
    lat: 41.9742,
    lon: -87.9073,
    tz: "America/Chicago",
  },
  SFO: {
    iata: "SFO",
    icao: "KSFO",
    city: {
      en: "San Francisco",
      zh: "旧金山",
      "zh-Hant": "舊金山",
      ja: "サンフランシスコ",
      es: "San Francisco",
      fr: "San Francisco",
      ru: "Сан-Франциско",
    },
    name: { en: "San Francisco Intl", zh: "旧金山国际机场" },
    country: { en: "United States", zh: "美国" },
    cc: "US",
    lat: 37.6213,
    lon: -122.379,
    tz: "America/Los_Angeles",
  },
  YYZ: {
    iata: "YYZ",
    icao: "CYYZ",
    city: {
      en: "Toronto",
      zh: "多伦多",
      "zh-Hant": "多倫多",
      ja: "トロント",
      es: "Toronto",
      fr: "Toronto",
      ru: "Торонто",
    },
    name: { en: "Pearson Intl", zh: "皮尔逊国际机场" },
    country: { en: "Canada", zh: "加拿大" },
    cc: "CA",
    lat: 43.6777,
    lon: -79.6248,
    tz: "America/Toronto",
  },
  DXB: {
    iata: "DXB",
    icao: "OMDB",
    city: {
      en: "Dubai",
      zh: "迪拜",
      "zh-Hant": "杜拜",
      ja: "ドバイ",
      es: "Dubái",
      fr: "Dubaï",
      ru: "Дубай",
    },
    name: { en: "Dubai Intl", zh: "迪拜国际机场" },
    country: { en: "United Arab Emirates", zh: "阿联酋" },
    cc: "AE",
    lat: 25.2532,
    lon: 55.3657,
    tz: "Asia/Dubai",
  },
  HKG: {
    iata: "HKG",
    // "Hong Kong" leads with the flag, exactly as "Singapore" does — asked
    // and measured: the summary endpoint returns Flag_of_Hong_Kong.svg.png.
    // The island's article leads with the skyline across the harbour.
    photoTitle: "Hong Kong Island",
    icao: "VHHH",
    city: {
      en: "Hong Kong",
      zh: "香港",
      "zh-Hant": "香港",
      ja: "香港",
      es: "Hong Kong",
      fr: "Hong Kong",
      ru: "Гонконг",
    },
    name: { en: "Hong Kong Intl", zh: "香港国际机场" },
    country: { en: "Hong Kong", zh: "中国香港" },
    cc: "HK",
    lat: 22.308,
    lon: 113.9185,
    tz: "Asia/Hong_Kong",
  },
  ICN: {
    iata: "ICN",
    icao: "RKSI",
    city: {
      en: "Seoul",
      zh: "首尔",
      "zh-Hant": "首爾",
      ja: "ソウル",
      es: "Seúl",
      fr: "Séoul",
      ru: "Сеул",
    },
    name: { en: "Incheon Intl", zh: "仁川国际机场" },
    country: { en: "South Korea", zh: "韩国" },
    cc: "KR",
    lat: 37.4602,
    lon: 126.4407,
    tz: "Asia/Seoul",
  },

  /**
   * East Asia, which this list barely had: one airport each in Shanghai,
   * Tokyo, Hong Kong and Seoul, and nothing at all in Beijing, Taipei or
   * the rest of the mainland. Every coordinate here was read off Wikipedia's
   * own geo data rather than remembered.
   */
  PEK: {
    iata: "PEK",
    icao: "ZBAA",
    city: {
      en: "Beijing",
      zh: "北京",
      "zh-Hant": "北京",
      ja: "北京",
      es: "Pekín",
      fr: "Pékin",
      ru: "Пекин",
    },
    name: { en: "Capital Intl", zh: "首都国际机场" },
    country: { en: "China", zh: "中国" },
    cc: "CN",
    lat: 40.0725,
    lon: 116.5975,
    tz: "Asia/Shanghai",
  },
  TPE: {
    iata: "TPE",
    icao: "RCTP",
    city: {
      en: "Taipei",
      zh: "台北",
      "zh-Hant": "台北",
      ja: "台北",
      es: "Taipéi",
      fr: "Taipei",
      ru: "Тайбэй",
    },
    name: { en: "Taoyuan Intl", zh: "桃园国际机场" },
    country: { en: "Taiwan", zh: "台湾" },
    cc: "TW",
    lat: 25.0764,
    lon: 121.2239,
    tz: "Asia/Taipei",
  },
  CAN: {
    iata: "CAN",
    icao: "ZGGG",
    city: {
      en: "Guangzhou",
      zh: "广州",
      "zh-Hant": "廣州",
      ja: "広州",
      es: "Cantón",
      fr: "Canton",
      ru: "Гуанчжоу",
    },
    name: { en: "Baiyun Intl", zh: "白云国际机场" },
    country: { en: "China", zh: "中国" },
    cc: "CN",
    lat: 23.3925,
    lon: 113.2989,
    tz: "Asia/Shanghai",
  },
  SZX: {
    iata: "SZX",
    icao: "ZGSZ",
    city: {
      en: "Shenzhen",
      zh: "深圳",
      "zh-Hant": "深圳",
      ja: "深圳",
      es: "Shenzhen",
      fr: "Shenzhen",
      ru: "Шэньчжэнь",
    },
    name: { en: "Bao'an Intl", zh: "宝安国际机场" },
    country: { en: "China", zh: "中国" },
    cc: "CN",
    lat: 22.6394,
    lon: 113.8108,
    tz: "Asia/Shanghai",
  },
  CTU: {
    iata: "CTU",
    icao: "ZUUU",
    city: {
      en: "Chengdu",
      zh: "成都",
      "zh-Hant": "成都",
      ja: "成都",
      es: "Chengdú",
      fr: "Chengdu",
      ru: "Чэнду",
    },
    name: { en: "Shuangliu Intl", zh: "双流国际机场" },
    country: { en: "China", zh: "中国" },
    cc: "CN",
    lat: 30.5783,
    lon: 103.9469,
    tz: "Asia/Shanghai",
  },
  NRT: {
    iata: "NRT",
    icao: "RJAA",
    city: {
      en: "Tokyo",
      zh: "东京",
      "zh-Hant": "東京",
      ja: "東京",
      es: "Tokio",
      fr: "Tokyo",
      ru: "Токио",
    },
    name: { en: "Narita Intl", zh: "成田国际机场" },
    country: { en: "Japan", zh: "日本" },
    cc: "JP",
    lat: 35.7653,
    lon: 140.3856,
    tz: "Asia/Tokyo",
  },
  KIX: {
    iata: "KIX",
    icao: "RJBB",
    city: {
      en: "Osaka",
      zh: "大阪",
      "zh-Hant": "大阪",
      ja: "大阪",
      es: "Osaka",
      fr: "Osaka",
      ru: "Осака",
    },
    name: { en: "Kansai Intl", zh: "关西国际机场" },
    country: { en: "Japan", zh: "日本" },
    cc: "JP",
    lat: 34.4306,
    lon: 135.2303,
    tz: "Asia/Tokyo",
  },
};
